In [1]:
import pandas as pd
covidf=pd.read_csv("C:\\Users\\Dnyaneshwari\\Downloads\\covid_19_data (1).csv")

In [2]:
covidf

,SNo,ObservationDate,Province/State,Country/Region,Last Update,Confirmed,Deaths,Recovered
0,1,01/22/2020,Anhui,Mainland China,1/22/2020 17:00,1.0,0.0,0.0
1,2,01/22/2020,Beijing,Mainland China,1/22/2020 17:00,14.0,0.0,0.0
2,3,01/22/2020,Chongqing,Mainland China,1/22/2020 17:00,6.0,0.0,0.0
3,4,01/22/2020,Fujian,Mainland China,1/22/2020 17:00,1.0,0.0,0.0
4,5,01/22/2020,Gansu,Mainland China,1/22/2020 17:00,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...
306424,306425,05/29/2021,Zaporizhia Oblast,Ukraine,2021-05-30 04:20:55,102641.0,2335.0,95289.0
306425,306426,05/29/2021,Zeeland,Netherlands,2021-05-30 04:20:55,29147.0,245.0,0.0
306426,306427,05/29/2021,Zhejiang,Mainland China,2021-05-30 04:20:55,1364.0,1.0,1324.0
306427,306428,05/29/2021,Zhytomyr Oblast,Ukraine,2021-05-30 04:20:55,87550.0,1738.0,83790.0
306428,306429,05/29/2021,Zuid-Holland,Netherlands,2021-05-30 04:20:55,391559.0,4252.0,0.0

In [12]:
covidf.shape

(306429, 8)

In [14]:
covidf.columns

Index(['SNo', 'ObservationDate', 'Province/State', 'Country/Region',
       'Last Update', 'Confirmed', 'Deaths', 'Recovered'],
      dtype='object')

In [15]:
covidf.dtypes

SNo                  int64
ObservationDate     object
Province/State      object
Country/Region      object
Last Update         object
Confirmed          float64
Deaths             float64
Recovered          float64
dtype: object

In [16]:
covidf.info

<bound method DataFrame.info of            SNo ObservationDate     Province/State  Country/Region  \
0            1      01/22/2020              Anhui  Mainland China
1            2      01/22/2020            Beijing  Mainland China
2            3      01/22/2020          Chongqing  Mainland China
3            4      01/22/2020             Fujian  Mainland China
4            5      01/22/2020              Gansu  Mainland China
...        ...             ...                ...             ...
306424  306425      05/29/2021  Zaporizhia Oblast         Ukraine
306425  306426      05/29/2021            Zeeland     Netherlands
306426  306427      05/29/2021           Zhejiang  Mainland China
306427  306428      05/29/2021    Zhytomyr Oblast         Ukraine
306428  306429      05/29/2021       Zuid-Holland     Netherlands

                Last Update  Confirmed  Deaths  Recovered
0           1/22/2020 17:00        1.0     0.0        0.0
1           1/22/2020 17:00       14.0     0.0        0.0
2           1/22/2020 17:00        6.0     0.0        0.0
3           1/22/2020 17:00        1.0     0.0        0.0
4           1/22/2020 17:00        0.0     0.0        0.0
...                     ...        ...     ...        ...
306424  2021-05-30 04:20:55   102641.0  2335.0    95289.0
306425  2021-05-30 04:20:55    29147.0   245.0        0.0
306426  2021-05-30 04:20:55     1364.0     1.0     1324.0
306427  2021-05-30 04:20:55    87550.0  1738.0    83790.0
306428  2021-05-30 04:20:55   391559.0  4252.0        0.0

[306429 rows x 8 columns]>

In [17]:
covidf.count()

SNo                306429
ObservationDate    306429
Province/State     228326
Country/Region     306429
Last Update        306429
Confirmed          306429
Deaths             306429
Recovered          306429
dtype: int64

In [23]:
a=covidf.Deaths.max()

In [24]:
a

112385.0

In [29]:
covidf.head()

,SNo,ObservationDate,Province/State,Country/Region,Last Update,Confirmed,Deaths,Recovered
0,1,01/22/2020,Anhui,Mainland China,1/22/2020 17:00,1.0,0.0,0.0
1,2,01/22/2020,Beijing,Mainland China,1/22/2020 17:00,14.0,0.0,0.0
2,3,01/22/2020,Chongqing,Mainland China,1/22/2020 17:00,6.0,0.0,0.0
3,4,01/22/2020,Fujian,Mainland China,1/22/2020 17:00,1.0,0.0,0.0
4,5,01/22/2020,Gansu,Mainland China,1/22/2020 17:00,0.0,0.0,0.0

In [30]:
covid.tail()

,SNo,ObservationDate,Province/State,Country/Region,Last Update,Confirmed,Deaths,Recovered
306424,306425,05/29/2021,Zaporizhia Oblast,Ukraine,2021-05-30 04:20:55,102641.0,2335.0,95289.0
306425,306426,05/29/2021,Zeeland,Netherlands,2021-05-30 04:20:55,29147.0,245.0,0.0
306426,306427,05/29/2021,Zhejiang,Mainland China,2021-05-30 04:20:55,1364.0,1.0,1324.0
306427,306428,05/29/2021,Zhytomyr Oblast,Ukraine,2021-05-30 04:20:55,87550.0,1738.0,83790.0
306428,306429,05/29/2021,Zuid-Holland,Netherlands,2021-05-30 04:20:55,391559.0,4252.0,0.0

In [31]:
covidf.isna().sum()

SNo                    0
ObservationDate        0
Province/State     78103
Country/Region         0
Last Update            0
Confirmed              0
Deaths                 0
Recovered              0
dtype: int64

In [32]:
covidf.iloc[5:15,0:4]

    SNo ObservationDate Province/State  Country/Region
5     6      01/22/2020      Guangdong  Mainland China
6     7      01/22/2020        Guangxi  Mainland China
7     8      01/22/2020        Guizhou  Mainland China
8     9      01/22/2020         Hainan  Mainland China
9    10      01/22/2020          Hebei  Mainland China
10   11      01/22/2020   Heilongjiang  Mainland China
11   12      01/22/2020          Henan  Mainland China
12   13      01/22/2020      Hong Kong       Hong Kong
13   14      01/22/2020          Hubei  Mainland China
14   15      01/22/2020          Hunan  Mainland China

In [36]:
covidf.loc[0:10,['Province/State','Country/Region']]

   Province/State  Country/Region
0           Anhui  Mainland China
1         Beijing  Mainland China
2       Chongqing  Mainland China
3          Fujian  Mainland China
4           Gansu  Mainland China
5       Guangdong  Mainland China
6         Guangxi  Mainland China
7         Guizhou  Mainland China
8          Hainan  Mainland China
9           Hebei  Mainland China
10   Heilongjiang  Mainland China

In [39]:
covidf

,SNo,ObservationDate,Province/State,Country/Region,Last Update,Confirmed,Deaths,Recovered
0,1,01/22/2020,Anhui,Mainland China,1/22/2020 17:00,1.0,0.0,0.0
1,2,01/22/2020,Beijing,Mainland China,1/22/2020 17:00,14.0,0.0,0.0
2,3,01/22/2020,Chongqing,Mainland China,1/22/2020 17:00,6.0,0.0,0.0
3,4,01/22/2020,Fujian,Mainland China,1/22/2020 17:00,1.0,0.0,0.0
4,5,01/22/2020,Gansu,Mainland China,1/22/2020 17:00,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...
306424,306425,05/29/2021,Zaporizhia Oblast,Ukraine,2021-05-30 04:20:55,102641.0,2335.0,95289.0
306425,306426,05/29/2021,Zeeland,Netherlands,2021-05-30 04:20:55,29147.0,245.0,0.0
306426,306427,05/29/2021,Zhejiang,Mainland China,2021-05-30 04:20:55,1364.0,1.0,1324.0
306427,306428,05/29/2021,Zhytomyr Oblast,Ukraine,2021-05-30 04:20:55,87550.0,1738.0,83790.0
306428,306429,05/29/2021,Zuid-Holland,Netherlands,2021-05-30 04:20:55,391559.0,4252.0,0.0

In [42]:
covidf[(covidf['Country/Region']=='Mainland China')]

,SNo,ObservationDate,Province/State,Country/Region,Last Update,Confirmed,Deaths,Recovered
0,1,01/22/2020,Anhui,Mainland China,1/22/2020 17:00,1.0,0.0,0.0
1,2,01/22/2020,Beijing,Mainland China,1/22/2020 17:00,14.0,0.0,0.0
2,3,01/22/2020,Chongqing,Mainland China,1/22/2020 17:00,6.0,0.0,0.0
3,4,01/22/2020,Fujian,Mainland China,1/22/2020 17:00,1.0,0.0,0.0
4,5,01/22/2020,Gansu,Mainland China,1/22/2020 17:00,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...
306340,306341,05/29/2021,Tibet,Mainland China,2021-05-30 04:20:55,1.0,0.0,1.0
306368,306369,05/29/2021,Unknown,Mainland China,2021-05-30 04:20:55,0.0,0.0,10.0
306412,306413,05/29/2021,Xinjiang,Mainland China,2021-05-30 04:20:55,980.0,3.0,977.0
306420,306421,05/29/2021,Yunnan,Mainland China,2021-05-30 04:20:55,352.0,2.0,331.0
306426,306427,05/29/2021,Zhejiang,Mainland China,2021-05-30 04:20:55,1364.0,1.0,1324.0

In [43]:
covidf[(covidf['Country/Region']=='Mainland China')].count()

SNo                15758
ObservationDate    15758
Province/State     15758
Country/Region     15758
Last Update        15758
Confirmed          15758
Deaths             15758
Recovered          15758
dtype: int64

In [4]:
m=covidf['Deaths'].min()

In [5]:
m

-178.0

In [7]:
n=covidf["Confirmed"].mean()

In [8]:
n

85670.91155863185

In [11]:
covidf['Deaths']

0            0.0
1            0.0
2            0.0
3            0.0
4            0.0
           ...
306424    2335.0
306425     245.0
306426       1.0
306427    1738.0
306428    4252.0
Name: Deaths, Length: 306429, dtype: float64

In [13]:
covidf['Province/State']

0                     Anhui
1                   Beijing
2                 Chongqing
3                    Fujian
4                     Gansu
                ...
306424    Zaporizhia Oblast
306425              Zeeland
306426             Zhejiang
306427      Zhytomyr Oblast
306428         Zuid-Holland
Name: Province/State, Length: 306429, dtype: object

In [14]:
covidf[(covidf['Province/State']=='Anhui')]

,SNo,ObservationDate,Province/State,Country/Region,Last Update,Confirmed,Deaths,Recovered
0,1,01/22/2020,Anhui,Mainland China,1/22/2020 17:00,1.0,0.0,0.0
40,41,01/23/2020,Anhui,Mainland China,1/23/20 17:00,9.0,0.0,0.0
99,100,01/24/2020,Anhui,Mainland China,1/24/20 17:00,15.0,0.0,0.0
137,138,01/25/2020,Anhui,Mainland China,1/25/20 17:00,39.0,0.0,0.0
184,185,01/26/2020,Anhui,Mainland China,1/26/20 16:00,60.0,0.0,0.0
...,...,...,...,...,...,...,...,...
302798,302799,05/25/2021,Anhui,Mainland China,2021-05-26 04:20:35,1004.0,6.0,989.0
303563,303564,05/26/2021,Anhui,Mainland China,2021-05-27 04:20:59,1004.0,6.0,990.0
304328,304329,05/27/2021,Anhui,Mainland China,2021-05-28 04:20:36,1004.0,6.0,992.0
305093,305094,05/28/2021,Anhui,Mainland China,2021-05-29 04:20:41,1004.0,6.0,994.0
305858,305859,05/29/2021,Anhui,Mainland China,2021-05-30 04:20:55,1004.0,6.0,994.0

In [15]:
covidf[(covidf['ObservationDate']=='01/22/2020')]

,SNo,ObservationDate,Province/State,Country/Region,Last Update,Confirmed,Deaths,Recovered
0,1,01/22/2020,Anhui,Mainland China,1/22/2020 17:00,1.0,0.0,0.0
1,2,01/22/2020,Beijing,Mainland China,1/22/2020 17:00,14.0,0.0,0.0
2,3,01/22/2020,Chongqing,Mainland China,1/22/2020 17:00,6.0,0.0,0.0
3,4,01/22/2020,Fujian,Mainland China,1/22/2020 17:00,1.0,0.0,0.0
4,5,01/22/2020,Gansu,Mainland China,1/22/2020 17:00,0.0,0.0,0.0
5,6,01/22/2020,Guangdong,Mainland China,1/22/2020 17:00,26.0,0.0,0.0
6,7,01/22/2020,Guangxi,Mainland China,1/22/2020 17:00,2.0,0.0,0.0
7,8,01/22/2020,Guizhou,Mainland China,1/22/2020 17:00,1.0,0.0,0.0
8,9,01/22/2020,Hainan,Mainland China,1/22/2020 17:00,4.0,0.0,0.0
9,10,01/22/2020,Hebei,Mainland China,1/22/2020 17:00,1.0,0.0,0.0
10,11,01/22/2020,Heilongjiang,Mainland China,1/22/2020 17:00,0.0,0.0,0.0
11,12,01/22/2020,Henan,Mainland China,1/22/2020 17:00,5.0,0.0,0.0
12,13,01/22/2020,Hong Kong,Hong Kong,1/22/2020 17:00,0.0,0.0,0.0
13,14,01/22/2020,Hubei,Mainland China,1/22/2020 17:00,444.0,17.0,28.0
14,15,01/22/2020,Hunan,Mainland China,1/22/2020 17:00,4.0,0.0,0.0
15,16,01/22/2020,Inner Mongolia,Mainland China,1/22/2020 17:00,0.0,0.0,0.0
16,17,01/22/2020,Jiangsu,Mainland China,1/22/2020 17:00,1.0,0.0,0.0
17,18,01/22/2020,Jiangxi,Mainland China,1/22/2020 17:00,2.0,0.0,0.0
18,19,01/22/2020,Jilin,Mainland China,1/22/2020 17:00,0.0,0.0,0.0
19,20,01/22/2020,Liaoning,Mainland China,1/22/2020 17:00,2.0,0.0,0.0
20,21,01/22/2020,Macau,Macau,1/22/2020 17:00,1.0,0.0,0.0
21,22,01/22/2020,Ningxia,Mainland China,1/22/2020 17:00,1.0,0.0,0.0
22,23,01/22/2020,Qinghai,Mainland China,1/22/2020 17:00,0.0,0.0,0.0
23,24,01/22/2020,Shaanxi,Mainland China,1/22/2020 17:00,0.0,0.0,0.0
24,25,01/22/2020,Shandong,Mainland China,1/22/2020 17:00,2.0,0.0,0.0
25,26,01/22/2020,Shanghai,Mainland China,1/22/2020 17:00,9.0,0.0,0.0
26,27,01/22/2020,Shanxi,Mainland China,1/22/2020 17:00,1.0,0.0,0.0
27,28,01/22/2020,Sichuan,Mainland China,1/22/2020 17:00,5.0,0.0,0.0
28,29,01/22/2020,Taiwan,Taiwan,1/22/2020 17:00,1.0,0.0,0.0
29,30,01/22/2020,Tianjin,Mainland China,1/22/2020 17:00,4.0,0.0,0.0
30,31,01/22/2020,Tibet,Mainland China,1/22/2020 17:00,0.0,0.0,0.0
31,32,01/22/2020,Washington,US,1/22/2020 17:00,1.0,0.0,0.0
32,33,01/22/2020,Xinjiang,Mainland China,1/22/2020 17:00,0.0,0.0,0.0
33,34,01/22/2020,Yunnan,Mainland China,1/22/2020 17:00,1.0,0.0,0.0
34,35,01/22/2020,Zhejiang,Mainland China,1/22/2020 17:00,10.0,0.0,0.0
35,36,01/22/2020,NaN,Japan,1/22/2020 17:00,2.0,0.0,0.0
36,37,01/22/2020,NaN,Thailand,1/22/2020 17:00,4.0,0.0,2.0
37,38,01/22/2020,NaN,South Korea,1/22/2020 17:00,1.0,0.0,0.0
38,39,01/22/2020,Unknown,China,1/22/2020 17:00,0.0,0.0,0.0
39,40,01/22/2020,NaN,Kiribati,1/22/2020 17:00,0.0,0.0,0.0

In [23]:
covidf[(covidf['ObservationDate']=="05/25/2021")]

,SNo,ObservationDate,Province/State,Country/Region,Last Update,Confirmed,Deaths,Recovered
302604,302605,05/25/2021,NaN,Afghanistan,2021-05-26 04:20:35,66903.0,2836.0,56518.0
302605,302606,05/25/2021,NaN,Albania,2021-05-26 04:20:35,132229.0,2447.0,128907.0
302606,302607,05/25/2021,NaN,Algeria,2021-05-26 04:20:35,127361.0,3433.0,88672.0
302607,302608,05/25/2021,NaN,Andorra,2021-05-26 04:20:35,13664.0,127.0,13263.0
302608,302609,05/25/2021,NaN,Angola,2021-05-26 04:20:35,32933.0,735.0,27204.0
...,...,...,...,...,...,...,...,...
303364,303365,05/25/2021,Zaporizhia Oblast,Ukraine,2021-05-26 04:20:35,101870.0,2270.0,93311.0
303365,303366,05/25/2021,Zeeland,Netherlands,2021-05-26 04:20:35,28938.0,245.0,0.0
303366,303367,05/25/2021,Zhejiang,Mainland China,2021-05-26 04:20:35,1363.0,1.0,1324.0
303367,303368,05/25/2021,Zhytomyr Oblast,Ukraine,2021-05-26 04:20:35,87225.0,1724.0,82158.0
303368,303369,05/25/2021,Zuid-Holland,Netherlands,2021-05-26 04:20:35,388457.0,4237.0,0.0

In [24]:
cat=[]
con=[]

for i in covidf.columns:
    if covidf[i].dtypes=="object":
        cat.append(i)
    else:
        con.append(i)

In [25]:
cat

['ObservationDate', 'Province/State', 'Country/Region', 'Last Update']

In [26]:
con

['SNo', 'Confirmed', 'Deaths', 'Recovered']

In [29]:
covidf["Deaths"].value_counts()

Deaths
0.0        32417
1.0         9799
2.0         6921
3.0         6107
6.0         4153
           ...
26172.0        1
50388.0        1
21467.0        1
13355.0        1
15268.0        1
Name: count, Length: 20089, dtype: int64

In [30]:
covidf["Last Update"].value_counts()

Last Update
2021-04-02 15:13:53    239885
3/8/20 5:31              1252
2021-05-30 04:20:55       765
2021-04-26 04:21:04       765
2021-04-20 04:20:41       765
                        ...
2020-03-10T10:33:02         1
2020-02-18T01:33:01         1
2020-03-10T01:33:02         1
2020-03-10T07:33:03         1
2020-02-04T03:03:07         1
Name: count, Length: 1905, dtype: int64

In [31]:
import matplotlib.pyplot as plt
import seaborn as sns

In [37]:
covidf[['','Deaths']].corr()

KeyError: "['Provices/State'] not in index"